### ISSUE TITLE
GPIO examples failed to compile on Kernel 6.10+

### ISSUE THREAD

**Issue by Integral-Tech** [sysprog21/lkmpg#285]
When compiling `intrpt.c`, `bottomhalf.c` or `bh_threaded.c` on Kernel 6.10+, the following errors will occur:
```
lkmpg/examples/bottomhalf.c: In function ‘bottomhalf_init’:
lkmpg/examples/bottomhalf.c:73:11: error: implicit declaration of function ‘gpio_request_array’; did you mean ‘gpio_request_one’? [-Wimplicit-function-declaration]
   73 |     ret = gpio_request_array(leds, ARRAY_SIZE(leds));
      |           ^~~~~~~~~~~~~~~~~~
      |           gpio_request_one
lkmpg/examples/intrpt.c: In function ‘intrpt_init’:
lkmpg/examples/intrpt.c:50:11: error: implicit declaration of function ‘gpio_request_array’; did you mean ‘gpio_request_one’? [-Wimplicit-function-declaration]
   50 |     ret = gpio_request_array(leds, ARRAY_SIZE(leds));
      |           ^~~~~~~~~~~~~~~~~~
      |           gpio_request_one
lkmpg/examples/bh_threaded.c: In function ‘bottomhalf_init’:
lkmpg/examples/bh_threaded.c:54:11: error: implicit declaration of function ‘gpio_request_array’; did you mean ‘gpio_request_one’? [-Wimplicit-function-declaration]
   54 |     ret = gpio_request_array(leds, ARRAY_SIZE(leds));
      |           ^~~~~~~~~~~~~~~~~~
      |           gpio_request_one
lkmpg/examples/bottomhalf.c:137:5: error: implicit declaration of function ‘gpio_free_array’; did you mean ‘gpiod_get_array’? [-Wimplicit-function-declaration]
  137 |     gpio_free_array(buttons, ARRAY_SIZE(leds));
      |     ^~~~~~~~~~~~~~~
      |     gpiod_get_array
lkmpg/examples/intrpt.c:114:5: error: implicit declaration of function ‘gpio_free_array’; did you mean ‘gpiod_get_array’? [-Wimplicit-function-declaration]
  114 |     gpio_free_array(buttons, ARRAY_SIZE(leds));
      |     ^~~~~~~~~~~~~~~
      |     gpiod_get_array
lkmpg/examples/bh_threaded.c:120:5: error: implicit declaration of function ‘gpio_free_array’; did you mean ‘gpiod_get_array’? [-Wimplicit-function-declaration]
  120 |     gpio_free_array(buttons, ARRAY_SIZE(leds));
      |     ^~~~~~~~~~~~~~~
      |     gpiod_get_array

```

Referring to [the source code of Linux 6.10](https://elixir.bootlin.com/linux/v6.11/source/include/linux/gpio.h), the function `gpio_request_array()` & `gpio_free_array()` has been completely removed, and [these Legacy GPIO API has been deprecated since Kernel 4.17](https://www.kernel.org/doc/html/v4.17/driver-api/gpio/legacy.html#api-reference):
> The functions listed in this section are deprecated. The GPIO descriptor based API should be used in new code.

Maybe we should migrate to the GPIO descriptor based API. which is recommended by kernel 4.17+.
