### PR TITLE
Update several example code for newer kernel

### PR DESCRIPTION
**Pull request by fennecJ**
Known issues with current example code:
If you using newer kernel(e.g linux 5.11.x) to compile the example code,
you may meet following error:
1. syscall.c:83:50: error: ‘ksys_close’ undeclared;
2. cryptosk.c:17:24: error: field ‘sg’ has incomplete type
3. cryptosk.c:143:9: error: implicit declaration of function
‘get_random_bytes’
4. error: macro "DECLARE_TASKLET" passed 3 arguments, but takes just 2

Solutions/workaround:
1. In syscall.c, replace #include <linux/syscalls.h> with
#include <linux/fdtable.h> and replace  ksys_close with close_fd
if the kernel version >= 5.11. [1][2]
2. Add #include <linux/scatterlist.h> into cryptosk.c
3. Add #include <linux/random.h> into cryptosk.c
4. In bottomhalf.c and example_tasklet.c, replace DECLARE_TASKLET
with DECLARE_TASKLET_OLD and dispose third argument(0L). [3]

[1] - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1572bfdf21d4d50e51941498ffe0b56c2289f783
[2] - https://www.mail-archive.com/meta-arago@arago-project.org//msg11939.html
[3] - https://patchwork.kernel.org/project/kernel-hardening/patch/20200716030847.1564131-3-keescook@chromium.org/

### CODE REVIEW

**Comment by fennecJ** [comment]
There are 2 things to worry about.

* 1. Currently I'm not sure if all module worked correctly after following changes.
* 2. Some function only worked on newer kernel ((e.g. `fd_close` only worked in kernel >= 5.11) , I currently
not sure if other version can compile the code via makefile smoothly.

My kernel version: 5.11.0-27-generic

**Comment by fennecJ** [comment]
The error/warning I've met with previous code:

`syscall.c`:
```bash
lkmpg/examples/syscall.c:83:50: error: ‘ksys_close’ undeclared (first use in this function); did you mean ‘ksys_chown’?
   83 |         if (sct[__NR_close] == (unsigned long *) ksys_close)
```
`cryptosk.c`:
```bash
lkmpg/examples/cryptosk.c:17:24: error: field ‘sg’ has incomplete type
   17 |     struct scatterlist sg;

lkmpg/examples/cryptosk.c:143:9: error: implicit declaration of function ‘get_random_bytes’ [-Werror=implicit-function-declaration]
  143 |         get_random_bytes(sk->ivdata, CIPHER_BLOCK_SIZE);

lkmpg/examples/cryptosk.c:156:5: error: implicit declaration of function ‘sg_init_one’ [-Werror=implicit-function-declaration]
  156 |     sg_init_one(&sk->sg, sk->scratchpad, CIPHER_BLOCK_SIZE);
```
`bottomhalf.c`:
`example_tasklet.c`:
```bash
error: macro "DECLARE_TASKLET" passed 3 arguments, but takes just 2
```

**Comment by fennecJ** [comment]
Seems like `DECLARE_TASKLET_OLD` is defined in `include/linux/interrupt.h` for kernel version >= v5.9
[https://elixir.bootlin.com/linux/v5.9-rc1/C/ident/DECLARE_TASKLET_OLD](https://elixir.bootlin.com/linux/v5.9-rc1/C/ident/DECLARE_TASKLET_OLD)

File: examples/syscall.c [hunk 1]
```diff
@@ -14,15 +14,30 @@
...
+ * after kernel 5.11, we need to replace it with close_fd instead.
+ */
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 11, 0))
+#include <linux/syscalls.h> /* For ksys_close */
+#else
+#include <linux/fdtable.h> /* For close_fd */
+#endif
+
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 11, 0))
+#define CLOSE_FUNC ksys_close
```
Comment (jserv) [inline examples/syscall.c:36]: You can simply define `close_fd` as `ksys_close`. That is,
```c
#define close_fd ksys_close
```

And move the definition right after the inclusion `#include <linux/syscalls.h>`.

File: examples/bottomhalf.c [hunk 2]
```diff
@@ -14,6 +14,10 @@
 #include <linux/kernel.h>
 #include <linux/module.h>
 
+#ifndef DECLARE_TASKLET_OLD
```
Comment (jserv) [inline examples/bottomhalf.c:17]: Add some notice from https://lwn.net/Articles/830964/

Comment (jserv) [reply examples/bottomhalf.c:39]: You can put the short description in the example code. The longer one should appear in TeX document.

File: examples/syscall.c [hunk 3]
```diff
@@ -14,15 +14,25 @@
...
  */
 #include <linux/sched.h>
 #include <linux/uaccess.h>
 
+/* The ksys_close in function aquire_sys_call_table is no longer support
+ * after kernel 5.11, we need to replace it with close_fd instead.
+ */
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 11, 0))
+#include <linux/syscalls.h> /* For ksys_close */
+#define close_fd ksys_close
```
Comment (jserv) [inline examples/syscall.c:31]: Append `for backward compatibility` in comment.

File: examples/bottomhalf.c [hunk 4]
```diff
@@ -14,6 +14,15 @@
 #include <linux/kernel.h>
 #include <linux/module.h>
 
+/* The API DECLARE_TASKLET should be replaced with DECLARE_TASKLET_OLD
```
Comment (jserv) [inline examples/bottomhalf.c:17]: Rewrite as following
> Macro DECLARE_TASKLET_OLD exists for compatibiity.
> See https://lwn.net/Articles/830964/

**Review by jserv — CHANGES_REQUESTED** [review]
Modify the the description in TeX document about DECLARE_TASKLET_OLD transition.

File: examples/syscall.c [hunk 5]
```diff
@@ -14,15 +14,25 @@
...
+#include <linux/unistd.h>      /* The list of system calls */
+#include <linux/version.h>
 
 /* For the current (process) structure, we need this to know who the
  * current user is.
  */
 #include <linux/sched.h>
 #include <linux/uaccess.h>
 
+/* The ksys_close in function aquire_sys_call_table is no longer support
```
Comment (jserv) [inline examples/syscall.c:26]: Correct the grammar.

**Comment by fennecJ** [comment]
There appears with a lot of `*.dwo` file after I using `make` in /example directory,
so I add `*.dwo` into `.gitignore` file.

File: examples/syscall.c [hunk 6]
```diff
@@ -14,15 +14,25 @@
...
  * current user is.
  */
 #include <linux/sched.h>
 #include <linux/uaccess.h>
 
+/* The ksys_close in function aquire_sys_call_table is no longer supported
+ * after kernel 5.11, we need to replace it with close_fd instead.
+ */
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 11, 0))
+#include <linux/syscalls.h> /* For ksys_close for backward compatibility */
```
Comment (jserv) [inline examples/syscall.c:30]: It was not intended to be "For ksys_close for backward compatibility." Instead, it should be
> ksys_close() wrapper for backward compatibility

File: examples/syscall.c [hunk 7]
```diff
@@ -14,15 +14,25 @@
...
+#include <linux/unistd.h>      /* The list of system calls */
+#include <linux/version.h>
 
 /* For the current (process) structure, we need this to know who the
  * current user is.
  */
 #include <linux/sched.h>
 #include <linux/uaccess.h>
 
+/* The ksys_close in function aquire_sys_call_table is no longer supported
```
Comment (jserv) [inline examples/syscall.c:26]: Change the comment to the following:
> The in-kernel calls to the sys_close() syscall were removed in Linux v5.11+.

File: lkmpg.tex [hunk 8]
```diff
@@ -1421,6 +1421,14 @@ \subsection{Tasklets}
 Example tasklet init continues...
 Example tasklet ends
 \end{verbatim}
+Although tasklet is easy to use, it comes with several defators and developers are discussing about getting rid of tasklet in linux kernel.
```
Comment (jserv) [inline lkmpg.tex:1424]: Add comma to separate.

File: lkmpg.tex [hunk 9]
```diff
@@ -1421,6 +1421,14 @@ \subsection{Tasklets}
...
+The tasklet callback runs in atomic context, inside a software interrupt, meaning that it cannot sleep or access user-space data, so not all work can be done in a tasklet handler.
+Also, the kernel only allows one instance of any given tasklet to be running at any given time; multiple different tasklet callbacks can run in parallel.
+
+In current kernels, tasklets can be replaced by workqueues, timers, or threaded interrupts.
+While the removal of tasklets remains a longer-term goal, the current kernel contains more than a hundred uses of tasklets.
+Now developers are proceeding with the API changes and the MACRO \cpp|DECLARE_TASKLET_OLD| exists for compatibiity.
```
Comment (jserv) [inline lkmpg.tex:1430]: Use lowercase "macro."

File: lkmpg.tex [hunk 10]
```diff
@@ -1421,6 +1421,14 @@ \subsection{Tasklets}
 Example tasklet init continues...
 Example tasklet ends
 \end{verbatim}
+Although tasklet is easy to use, it comes with several defators, and developers are discussing about getting rid of tasklet in linux kernel.
+The tasklet callback runs in atomic context, inside a software interrupt, meaning that it cannot sleep or access user-space data, so not all work can be done in a tasklet handler.
+Also, the kernel only allows one instance of any given tasklet to be running at any given time; multiple different tasklet callbacks can run in parallel.
+
+In current kernels, tasklets can be replaced by workqueues, timers, or threaded interrupts.
```
Comment (jserv) [inline lkmpg.tex:1428]: Should "recent kernels" rather than "current kernels" according to the context.

Comment (jserv) [reply lkmpg.tex:1428]: It is the first time that "threaded interrupt" is mentioned. You should add footnote such as
> The goal of threaded interrupts is to push more of the work to separate threads, so that the minimum needed for acknowledging an interrupt is reduced, and therefore the time spent handling the interrupt (where it can't handle any other interrupts at the same time) is reduced.
> See https://lwn.net/Articles/302043/

Comment (jserv) [reply lkmpg.tex:1428]: In case you didn't know about threaded interrupt, you can check the slides: https://elinux.org/images/e/ef/InterruptThreads-Slides_Anderson.pdf
I was discussing on threaded interrupts and RT as well. See https://hackmd.io/@sysprog/preempt-rt

**Comment by fennecJ** [comment]
"fn-in" in Makefile is intended to prevent make4ht from
excluding footnote into a new html file.

File: lkmpg.tex [hunk 11]
```diff
@@ -1421,6 +1421,16 @@ \subsection{Tasklets}
 Example tasklet init continues...
 Example tasklet ends
 \end{verbatim}
+Although tasklet is easy to use, it comes with several defators, and developers are discussing about getting rid of tasklet in linux kernel.
+The tasklet callback runs in atomic context, inside a software interrupt, meaning that it cannot sleep or access user-space data, so not all work can be done in a tasklet handler.
+Also, the kernel only allows one instance of any given tasklet to be running at any given time; multiple different tasklet callbacks can run in parallel.
+
+In recent kernels, tasklets can be replaced by workqueues, timers, or threaded interrupts\footnotemark.
```
Comment (jserv) [inline lkmpg.tex:1428]: Why can't you append `\footnote` right after threaded interrupts?
That is,
> In recent kernels, tasklets can be replaced by workqueues, timers, or threaded interrupts.\footnote{The goal of threaded interrupts is to push more of the work to separate threads ...}

**Comment by jserv** [comment]
Thank @fennecJ for the great work!
